### ISSUE TITLE
[Tab list idea] EXPANDABLE_FIXED_SIZE type

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/TabOverlayCommon#2]
With this issue would I like to propose a new Tab list type to utilize. The `EXPANDABLE_FIXED_SIZE` tab list (Name could be changed if desired. Alternatively could it be a config option for the `FIXED_SIZE` tab).

I post this here, since it could be used on both BTLP and ATO.

## What does it do?
The `EXPANDABLE_FIXED_SIZE` would essentially be a actual hybrid between `DYNAMIC_SIZE` and `FIXED_SIZE`

Unlike the `columns` option for the `FIXED_SIZE` tab would this one make the tab list increase its column count if the amount of used slots exceeds a specific value.
As an example: If a tab with 20 slots gets one additional player, which increases the total of slots to 21, would it automatically adjust itself to 2 columns, rearanging any custom slots and players where necessary.

## New placeholders
With this new type would of course come new challenges in terms of tab list designs, as a design made for 2 columns could break when the tab increases to 3 or reduces to 1.
For that do I suggest some new placeholders and components to utilize here.

### `!row`
The `!row` component would be similar to the `!spacer` but with the difference that it would fill slots in a horizontal order and ONLY 1 row (Or the number of rows required for the provided components, if you have `fillSlotsVertical` active.)

Here is the possible syntax to use:
```yaml
- !row
  component: # Would fill each column with an empty and filled slot vertically.
  - {}
  - {center: "&7==============="}
  fillSlotsVertical: true
```

### `${tablist}`
The could be a `${tablist}` component that could be utilized for various things like in `!conditional` parts.
When adding `size` to it `${tablist size}` could it return the total amount of slots currently used and when using something like `${tablist columns size}` would it instead return the total amount of columns a tab list has.

This would be useful for custom text where changing columns size could become problematic.

Example use-case (I don't know if !switch would work for components, so just assume it does):
```yaml
- !switch
  expression: "${tablist columns size}"
  replacements:
    "2":
    - {center: "&7Welcome"}
    - {center: "&a${viewer name}"}
    "3":
    - {}
    - {center: "&7Welcome"}
    - {}
    - {}
    - {center: "&a${viewer name}"}
    - {}
    "4":
    - {}
    - {center: "&7Welcome"}
    - {center: "&a${viewer name}"}
    - {}
  defaultReplacement: # Just one column in this case
  - {center: "&7Welcome"}
  - {center: "&a${viewer name}"}
```

## Example
Here's an example I once created showcasing how this could look like when utilized.

Config:
```yaml
type: EXPANDABLE_FIXED_SIZE
columns: 20

components:
- !switch
  expression: "${tablist columns size}"
  replacements:
    "3":
    - {}
    - {center: "&7Welcome"}
    - {}
    - {}
    - {center: "&a${viewer name}"}
    - {}
    "4":
    - {}
    - {center: "&7Welcome"}
    - {center: "&a${viewer name}"}
    - {}
  defaultReplacement:
  - {center: "&7Welcome"}
  - {center: "&a${viewer name}"}
- !row
  components: # Would fill a row of 2 slots
  - {}
  - {center: "&7==============="}
  fillSlotsVertical: true
- !players
  playerSet: all_players
  playerComponent: "${player name}"
- !row{} # Defaults to a single row of empty slots
- !switch
  expression: "${tablist columns size}"
  replacements:
    "2":
    - {text: "&7Website"}
    - {text: "https://example.com"}
    "3":
    - {text: "&7Website"}
    - {}
    - {text: "https://example.com"}
    "4":
    - {}
    - {text: "&7Website"}
    - {text: "https://example.com"}
    - {}
  defaultReplacement:
  - {center: "&7Website"}
  - {center: "https://example.com"}
```

Results:

- 1 column
  ![example 1](https://cdn.discordapp.com/attachments/699946184692858930/812696967988903946/2021-02-20_15.46.42.png)
- 2 columns
  ![example 2](https://cdn.discordapp.com/attachments/699946184692858930/812696946493882398/2021-02-20_15.45.48.png)
- 3 columns
  ![example 3](https://cdn.discordapp.com/attachments/699946184692858930/812696918320742420/2021-02-20_15.44.23.png)

## But why?
I and probably many people assumed that the `columns` option for the `FIXED_SIZE` tab was an actual hybrid of dynamic and fixed size, bringing us the ability of custom slots with having a dynamically expanding tab list.

This, however, isn't the case and the `columns` option is basically pointless as its only benefit is, that it *can* slightly expand the number of rows, if the size is between two values resulting in the same column count (i.e. 20 and 30 rows).
It isn't that useful for most cases tho and actually a rather pointless addition to the tab list plugins.

Having an actual option that would allow us to combine benefits of both types would truly allow people to create wonderful tab lists for their servers and/or networks.

## Credits
This idea was originally a [Suggestion](https://discord.com/channels/693095705421545563/699946184692858930/812696788665499669) by me from the Discord server, but I decided to make an issue out of it, to properly track it, as I fear that the suggestion might get lost otherwise.
